{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }} 
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  ingress:
  {{- if .Values.ingress.enabled }}
  - from:
    {{/* TODO: other popular ingress classes */}}
    {{- if eq "nginx" (lower .Values.ingress.class) }}
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    {{- end }}
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  {{- end }}
  policyTypes:
  - Ingress
{{- end }}
