{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4}}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
{{- end }}
